### ISSUE TITLE
Adding Priority and Severity

### ISSUE THREAD

**Issue by chikki78** [nonealexq/jmeter-allure-reporting#2]
How to add the Priority and Severity to the report.
what are the annotations for them to be added to the report?
Your help is appreciated.
We have the annotations for Selenium but i am looking the annotations for JMeter allure reports

**Comment by nonealexq** [comment]
We will update the repository soon. Refactored and added many interesting features :)

**Comment by nonealexq** [comment]
https://github.com/nonealexq/jmeter-allure-reporting/tree/v1.4.11#add-any-custom-label
Update .groovy to use it
And just write :)
`vars.put("allure.label.severity","critical");`
