### ISSUE TITLE
Не работает объявление issues

### ISSUE THREAD

**Issue by mobikylym** [nonealexq/jmeter-allure-reporting#6]
Добрый день!
Подскажите, как добавить к кейсу issues? Пробовал уже и в параметрах Allure.log.info, и в Declare allure annotations - ничего не работает. Возможно я использую неправильный синтаксис.

**Comment by nonealexq** [comment]
День добрый, подскажите в каком виде вы смотрите на отчет?
В Allure TMS или через стандартные средства генерации отчетов?

allure generate allure-results/ --clean -o allure-report
allure open allure-report/

?

**Comment by nonealexq** [comment]
Если используете TMS AllureTestOps - то можно писать allure.label.issue - и матчить его с ключом из ТМС 
<img width="1269" alt="image" src="https://github.com/nonealexq/jmeter-allure-reporting/assets/30975418/2397a410-7e8e-40a2-b3cb-2c356972e152">

Если используете классическую генерацию формата аллур через allure generate allure-results/ --clean -o allure-report - то подготовил ветку с возможностью добавлять линк через allure.link (пока один, если надо будет несколько - то сделаем)

https://github.com/nonealexq/jmeter-allure-reporting/tree/issue-6-add-link-support#add-link - дока с измененным allure-reporter.groovy

MR: 
https://github.com/nonealexq/jmeter-allure-reporting/pull/7

**Comment by mobikylym** [comment]
@nonealexq 
Недавно начал работать с Allure (после прочтения вашей статьи на хабре), затрудняюсь ответить, в каком виде использую. Но скорее всего через стандартные средства - отчёт генерирую с плагина для Jenkins в послесборочных операциях.
Я правильно понял, что issue в том виде, в котором есть сейчас в allure-reporter.groovy, будет работать только при должной конфигурации Allure TMS, а при использовании стандартных средств необходимо пользоваться линками?

**Comment by nonealexq** [comment]
Да, все правильно. Стандартная генерация отчета подразумевает задачи только в линках - на то дело сготовил отдельную ветку

**Comment by nonealexq** [comment]
Переделал под универсальное использование и по заветам аллура)
Просто используйте данный синтаксис

vars.put("allure.link.issue","https://github.com/nonealexq/jmeter-allure-reporting/issues/6");

Где issue - это имя ссылки, оно может быть любым - далее значение = ссылки

**Comment by mobikylym** [comment]
Большое спасибо за развёрнутые ответы и внесённые доработки. Разобрался, всё работает!
Хочу внести свою лепту в доработки файла allure-reporter.groovy. Здесь
[allure-reporter.groovy.zip](https://github.com/nonealexq/jmeter-allure-reporting/files/11998627/allure-reporter.groovy.zip)
 я починил теги и переделал линки (чтобы удачно ложились на параметризованные тесты в любом количестве). Если вам будет интересно, могу приложить скрины с синтаксисом использования в интерфейсе JMeter.
Моя компания заинтересована в развитии данного инструмента)

**Comment by nonealexq** [comment]
@mobikylym создавай фор с пул реквестом, посмотрим и смержим)

Я только за :)

**Comment by mobikylym** [comment]
Готово: https://github.com/nonealexq/jmeter-allure-reporting/commit/ec9e490e3a93a3a725339ff82b77383a8410135a
Приложил скрины с использованием тегов и линков. Будем рады плодотворному сотрудничеству)

**Comment by nonealexq** [comment]
Посмотрел, отписался :)
Давай чтоли новое ишью создадим ради такого, шоб по красоте было все
